---
- hosts: all
  sudo: yes
  gather_facts: False
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - docker-engine
      - git
    pip_packages:
      - pip
      - docker-compose

  tasks:
    - name: add docker repo
      apt_repository:
        repo: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
        state: present
        filename: 'docker'

    - name: get docker repo key
      apt_key:
        keyserver: 'hkp://ha.pool.sks-keyservers.net:80'
        id: '58118E89F3A912897C070ADBF76221572C52609D'

    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes
        dpkg_options: 'force-confold,force-confdef'

    - name: install {{item}}
      apt: name={{item}}
           state=latest
           install_recommends=yes
      with_items:
        - "{{packages}}"

    - name:  install {{item}}
      pip:
        name: "{{item}}"
        state: forcereinstall
      with_items:
        - "{{pip_packages}}"

    - name: restart docker service
      service:
        name=docker
        state=restarted
